"""
Deterministic renderer for `.prompts` files.

We intentionally hand-roll this rather than lean on a general TOML writer:

  - The rendered shape (field order, indent, multi-line string form) is part
    of the contract. Two runs of `spec prompts capture` over the same
    input must produce byte-identical output.
  - Long user prompts deserve multi-line literal strings (`'''…'''`), which
    general writers rarely emit by default.
  - Inline tables for `tool_calls.args` keep each tool call on a small
    number of lines, which is critical for diff readability in reviews.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any

from .schema import (
    DEFAULT_VISIBILITY,
    SCHEMA_VERSION,
    CommitMeta,
    PromptsEdit,
    PromptsFile,
    Session,
    ToolCall,
    Turn,
    validate_prompts_file,
)
from .text_sanitize import sanitize_for_toml_text

# ---------------------------------------------------------------------------
# Header — fixed text so two renders match byte-for-byte.
# ---------------------------------------------------------------------------

_HEADER_COMMENT = (
    "# Auto-generated by `spec prompts capture`. Safe to edit —\n"
    "# changes here alter what the compiler sees on the next run.\n"
    "# Spec: https://spec.lightreach.io/docs/prompt-format\n"
)


# ---------------------------------------------------------------------------
# Primitive emitters
# ---------------------------------------------------------------------------

_BASIC_ESCAPES: dict[str, str] = {
    "\\": "\\\\",
    '"': '\\"',
    "\b": "\\b",
    "\t": "\\t",
    "\n": "\\n",
    "\f": "\\f",
    "\r": "\\r",
}


def _basic_quote(s: str) -> str:
    """Emit a TOML basic string `"..."` with the full escape set."""
    out: list[str] = []
    for ch in s:
        if ch in _BASIC_ESCAPES:
            out.append(_BASIC_ESCAPES[ch])
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _iso_z(dt: datetime) -> str:
    """TOML offset datetime literal, always UTC with trailing `Z`."""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


_BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")


def _key(k: str) -> str:
    if _BARE_KEY.match(k):
        return k
    return _basic_quote(k)


def _inline_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        # Reject NaN / inf — not valid TOML, would silently break the file.
        if v != v or v in (float("inf"), float("-inf")):
            raise ValueError("NaN/inf are not representable in TOML")
        return repr(v)
    if isinstance(v, str):
        return _basic_quote(v)
    if isinstance(v, datetime):
        return _iso_z(v)
    if isinstance(v, list):
        return "[" + ", ".join(_inline_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return _inline_table(v)
    raise TypeError(f"unsupported TOML inline value: {type(v).__name__}")


def _inline_table(d: dict[str, Any]) -> str:
    """`{ k = v, k = v }` — keys sorted alphabetically for byte-stability."""
    if not d:
        return "{ }"
    parts = [f"{_key(k)} = {_inline_value(d[k])}" for k in sorted(d.keys())]
    return "{ " + ", ".join(parts) + " }"


def _string_array(values: list[str], *, indent: str = "") -> str:
    """Emit a string array. Short arrays go inline; long ones break across
    lines so diffs stay reviewable."""
    if not values:
        return "[]"
    inline = "[" + ", ".join(_basic_quote(v) for v in values) + "]"
    if len(inline) <= 80 and "\n" not in inline:
        return inline
    lines = ["["]
    for v in values:
        lines.append(f"{indent}  {_basic_quote(v)},")
    lines.append(f"{indent}]")
    return "\n".join(lines)


def _render_text_field(key: str, value: str, *, indent: str = "") -> str:
    """
    Choose the best representation for a string field:
      - multi-line literal (`'''…'''`) for anything with a newline or >80
        chars, and no `'''` substring
      - multi-line basic (`\"\"\"…\"\"\"`) as the rare fallback when the
        content contains `'''`
      - basic string (`"…"`) for short single-line text
    """
    value = sanitize_for_toml_text(value)
    if "\n" in value or len(value) > 80:
        canonical = value if value.endswith("\n") else value + "\n"
        if "'''" not in canonical:
            return f"{indent}{key} = '''\n{canonical}{indent}'''"
        # Rare fallback: escape backslashes and split any `"""` run.
        escaped = canonical.replace("\\", "\\\\")
        escaped = re.sub(r'"""', r'""\\"', escaped)
        return f'{indent}{key} = """\n{escaped}{indent}"""'
    return f"{indent}{key} = {_basic_quote(value)}"


# ---------------------------------------------------------------------------
# Commit / session / edit / turn emitters
# ---------------------------------------------------------------------------

# Fixed order for [commit] fields — part of the contract.
_COMMIT_FIELD_ORDER: tuple[str, ...] = (
    "branch",
    "message",
    "committed_at",
    "author_name",
    "author_email",
    "author_username",
)


def _render_commit(commit: CommitMeta) -> list[str]:
    lines: list[str] = ["[commit]"]
    for field_name in _COMMIT_FIELD_ORDER:
        value = getattr(commit, field_name)
        if value is None:
            continue
        if isinstance(value, datetime):
            lines.append(f"{field_name} = {_iso_z(value)}")
        else:
            lines.append(f"{field_name} = {_basic_quote(value)}")
    return lines


# Fixed order for [[sessions]] fields — part of the contract.
_SESSION_FIELD_ORDER: tuple[str, ...] = (
    "id",
    "source",
    "started_at",
    "ended_at",
    "model",
    "cwd",
    "operator",
    "title",
    "summary",
    "lesson",
    "tags",
    "outcome",
    "visibility",
    "forked_from",
    "paths_touched",
    "verbose",
)

# Fields that need multi-line string treatment when long.
_SESSION_TEXT_FIELDS: frozenset[str] = frozenset({"summary", "lesson", "title"})


def _render_session_header(session: Session) -> list[str]:
    lines: list[str] = ["[[sessions]]"]
    for field_name in _SESSION_FIELD_ORDER:
        value = getattr(session, field_name)
        # Skip defaults and empties.
        if value is None:
            continue
        if field_name == "verbose" and value is False:
            continue
        if field_name == "visibility" and value == DEFAULT_VISIBILITY:
            # Omit the default so hand-authored files stay minimal.
            continue
        if field_name in ("tags", "paths_touched") and not value:
            continue
        if field_name == "forked_from" and not value:
            continue

        if isinstance(value, datetime):
            lines.append(f"{field_name} = {_iso_z(value)}")
        elif isinstance(value, bool):
            lines.append(f"{field_name} = {'true' if value else 'false'}")
        elif isinstance(value, list):
            lines.append(f"{field_name} = {_string_array(value)}")
        elif field_name in _SESSION_TEXT_FIELDS and isinstance(value, str):
            lines.append(_render_text_field(field_name, value))
        else:
            lines.append(f"{field_name} = {_basic_quote(value)}")
    return lines


def _render_edit(edit: PromptsEdit) -> list[str]:
    lines = ["[[edits]]"]
    lines.append(f"at       = {_iso_z(edit.at)}")
    lines.append(f"by       = {_basic_quote(edit.by)}")
    if edit.sessions:
        lines.append(f"sessions = {_string_array(edit.sessions)}")
    turns_str = "[" + ", ".join(str(i) for i in edit.turns) + "]"
    lines.append(f"turns    = {turns_str}")
    if edit.reason:
        lines.append(f"reason   = {_basic_quote(edit.reason)}")
    return lines


def _render_tool_call(call: ToolCall) -> list[str]:
    # Tool calls live under a turn. Indented two levels to visually nest in
    # text editors — TOML itself doesn't care about whitespace.
    lines = ["    [[sessions.turns.tool_calls]]"]
    lines.append(f"    name = {_basic_quote(call.name)}")
    if call.status:
        lines.append(f"    status = {_basic_quote(call.status)}")
    lines.append(f"    args = {_inline_table(call.args)}")
    return lines


def _render_turn(turn: Turn) -> list[str]:
    lines = ["  [[sessions.turns]]"]
    lines.append(f"  role = {_basic_quote(turn.role)}")
    if turn.at is not None:
        lines.append(f"  at   = {_iso_z(turn.at)}")
    if turn.summary is not None:
        lines.append(f"  summary = {_basic_quote(turn.summary)}")
    if turn.text is not None:
        lines.append(_render_text_field("text", turn.text, indent="  "))
    for call in turn.tool_calls:
        lines.append("")
        lines.extend(_render_tool_call(call))
    return lines


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_prompts_file(pf: PromptsFile) -> str:
    """Render a PromptsFile into the exact bytes we'd write to disk.

    Validates first: we never emit a file that wouldn't parse back into an
    equivalent PromptsFile.
    """
    validate_prompts_file(pf)

    out: list[str] = []
    out.append(f'schema = "{SCHEMA_VERSION}"')
    out.append("")
    out.append(_HEADER_COMMENT.rstrip("\n"))
    out.append("")
    out.extend(_render_commit(pf.commit))

    # Sessions, deterministically ordered: (started_at, id). Absent
    # timestamps sort to the end so the corpus reads chronologically when
    # the capture gave us timestamps, and deterministically otherwise.
    ordered = sorted(
        pf.sessions,
        key=lambda s: (
            s.started_at is None,
            s.started_at or datetime.max.replace(tzinfo=timezone.utc),
            s.id,
        ),
    )

    for session in ordered:
        out.append("")
        out.extend(_render_session_header(session))
        for turn in session.turns:
            out.append("")
            out.extend(_render_turn(turn))

    for edit in pf.edits:
        out.append("")
        out.extend(_render_edit(edit))

    return "\n".join(out) + "\n"


def prompts_filename(now: datetime | None = None) -> str:
    """Canonical filename for a `.prompts` file under `prompts/`.

    `<ISO8601-seconds-Z>.prompts`
    with `:` replaced by `-` so the filename is portable across filesystems.
    """
    ts = now or datetime.now(timezone.utc)
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    stamp = ts.astimezone(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    return f"{stamp}.prompts"


__all__ = ["render_prompts_file", "prompts_filename"]
