"""Human-readable mirror of team editing state for agents and humans.

``.spec/team-editing-brief.md`` is regenerated whenever
``.spec/team-presence.json`` changes. IDEs and rules can point models at
this file without parsing JSON.

``mirror_stale`` answers whether ``team-presence.json`` is too old to
trust for coordination (``spec watch`` likely not running).
"""
from __future__ import annotations

import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

TEAM_EDITING_BRIEF_FILENAME = "team-editing-brief.md"
# If ``updated_at`` on the JSON is older than this, ``spec locks check``
# treats the mirror as stale and fails open (exit 0).
DEFAULT_LOCKS_MIRROR_STALE_SECS = 900.0


def _parse_iso_utc(raw: Any) -> datetime | None:
    if not raw or not isinstance(raw, str):
        return None
    s = raw.strip().replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(s).astimezone(timezone.utc)
    except ValueError:
        return None


def _compute_pull_alerts(body: dict[str, Any]) -> list[dict[str, str]]:
    """Peers whose ``head_commit`` is on the same branch as ``self`` but
    differs — i.e. they have probably just pushed and the viewer is
    behind. Returns a list of alert dicts the renderer surfaces in the
    "Pull needed" section.

    Rules:

    * Skip if ``self.head_commit`` is missing — we can't compare.
    * Skip if the peer is on a different branch than ``self.branch``.
      Cross-branch staleness is normal; only intra-branch divergence
      is a "pull before you edit" signal.
    * Skip if the peer's ``head_commit`` matches ``self.head_commit``.
    * Skip if the peer has no ``head_commit`` recorded.

    Returns a stable-sorted list of ``{"handle", "branch",
    "short_commit", "self_short"}`` dicts; one entry per stale peer.
    The renderer caps the visible text but we return the full list so
    a future ``spec locks check --json`` consumer can show all of
    them.
    """
    self_block = body.get("self") if isinstance(body.get("self"), dict) else None
    if not self_block:
        return []
    self_commit = self_block.get("head_commit")
    self_branch = self_block.get("branch")
    if not isinstance(self_commit, str) or not self_commit:
        return []
    if not isinstance(self_branch, str) or not self_branch:
        # No branch on local — we cannot tell whether peer divergence
        # is meaningful. Better to stay quiet than cry "pull!" on a
        # detached HEAD.
        return []

    members = body.get("members") or []
    if not isinstance(members, list):
        return []

    self_short = self_commit[:7]
    alerts: list[dict[str, str]] = []
    for m in members:
        if not isinstance(m, dict):
            continue
        peer_commit = m.get("head_commit")
        peer_branch = m.get("branch")
        peer_handle = m.get("handle") or m.get("name") or "(unknown)"
        if not isinstance(peer_commit, str) or not peer_commit:
            continue
        if not isinstance(peer_branch, str) or peer_branch != self_branch:
            continue
        if peer_commit == self_commit:
            continue
        alerts.append(
            {
                "handle": str(peer_handle),
                "branch": peer_branch,
                "short_commit": peer_commit[:7],
                "self_short": self_short,
            }
        )
    alerts.sort(key=lambda a: a["handle"])
    return alerts


def team_presence_mirror_stale(
    body: dict[str, Any] | None, *, max_age_secs: float = DEFAULT_LOCKS_MIRROR_STALE_SECS
) -> bool:
    """True when the mirror should not be trusted for edit coordination.

    Missing body, missing ``updated_at``, unparseable timestamps, or
    ``updated_at`` older than ``max_age_secs`` → stale.
    """
    if not body:
        return True
    ts = _parse_iso_utc(body.get("updated_at"))
    if ts is None:
        return True
    age = (datetime.now(timezone.utc) - ts).total_seconds()
    return age > max_age_secs


def render_team_editing_brief(
    body: dict[str, Any],
    *,
    active_edits: list[dict[str, Any]] | None = None,
) -> str:
    """Markdown summary derived from the same dict written to
    ``team-presence.json``.

    ``active_edits`` is an optional list of *local* per-machine
    locks (see :mod:`spec_cli.realtime.active_edits`). They have
    nothing to do with teammates — they coordinate a *single user's*
    multiple AI agents (Cursor + Claude Code + Codex) on the same
    machine. Surfacing them in the brief means a hook reading the
    one canonical file (``team-editing-brief.md``) sees both layers
    of "who is editing what" without parsing two JSONs.
    """
    lines: list[str] = [
        "# Spec Live — team editing (auto-generated)",
        "",
        "Regenerated by `spec watch` when `.spec/team-presence.json` changes.",
        "Before planning, also read `.spec/team-coordination.md` when present",
        "for active objectives, progress, claimed paths, and recent handoffs.",
        "Read this (or run `spec locks check <path>`) before editing files",
        "other teammates — or your own other AI agents — may be touching.",
        "",
    ]
    updated = body.get("updated_at")
    if isinstance(updated, str) and updated:
        lines.append(f"**Mirror updated:** {updated} (UTC)")
        lines.append("")

    # ── git push handoffs (YAML + JSON mirror) ────────────────────
    push_req = body.get("push_requests")
    if isinstance(push_req, list) and push_req:
        lines.append("## Git push handoff — read `.spec/team-push-requests.yaml`")
        lines.append("")
        lines.append(
            "**Canonical file:** `.spec/team-push-requests.yaml` (YAML). "
            "The rows below are copied into this brief and "
            "`.spec/team-presence.json` under `push_requests` so every AI "
            "tool sees them. If **your** Spec handle matches `to_handle`, "
            "help the user **commit** if needed and **`git push`** to "
            "`origin` on the listed branch (never force-push unless the "
            "user explicitly asks)."
        )
        lines.append("")
        for row in push_req:
            if not isinstance(row, dict):
                continue
            to_h = row.get("to_handle") or "?"
            from_h = row.get("from_handle")
            from_d = row.get("from_display")
            if not from_d:
                from_d = f"@{from_h}" if from_h else "(unknown)"
            br = row.get("branch") or "(branch unknown)"
            msg = row.get("message")
            exp = row.get("expires_at") or "?"
            lines.append(
                f"- **@{to_h}** is asked to push — from {from_d} · branch `{br}` "
                f"· expires `{exp}`"
                + (f" · note: {msg}" if msg else "")
            )
        lines.append("")

    members = body.get("members") or []
    if not isinstance(members, list):
        members = []

    # ── single-user multi-agent locks ─────────────────────────────
    # Active edits are per-machine, not per-team. They tell an AI
    # agent "your Cursor pane has auth.py locked right now — don't
    # also write to it from Claude Code". Listed before the team
    # section because a same-machine lock is the closest, most-
    # certain conflict — peers might be stale, your own Cursor
    # writing right now is not.
    if active_edits:
        lines.append("## Your own AI agents currently editing")
        lines.append("")
        for lock in active_edits:
            if not isinstance(lock, dict):
                continue
            agent = lock.get("agent") or "agent"
            session = lock.get("session_id") or "-"
            intent = lock.get("intent") or "-"
            expires = lock.get("expires_at") or "-"
            paths = lock.get("paths") or []
            if not isinstance(paths, list):
                paths = []
            paths_fmt = ", ".join(f"`{p}`" for p in paths) or "_no paths_"
            lines.append(
                f"- **{agent}** (session `{session}`, intent `{intent}`) — "
                f"editing {paths_fmt}; expires {expires}"
            )
        lines.append("")

    # ── pull-needed section ───────────────────────────────────────
    # When a teammate's head_commit on the same branch differs from
    # ``self.head_commit``, they have probably just pushed and we are
    # behind. Surface this *before* the dirty-files list so an AI
    # IDE / hook can react first ("git pull, then edit") rather than
    # last ("edit, conflict on pull"). The brief is the single
    # readable file every hook / IDE looks at, so the pull-needed
    # signal belongs here.
    pull_alerts = _compute_pull_alerts(body)
    if pull_alerts:
        lines.append("## Pull needed — teammates pushed new commits")
        lines.append("")
        for alert in pull_alerts:
            lines.append(
                f"- @{alert['handle']} on `{alert['branch']}` "
                f"is at `{alert['short_commit']}` (you: `{alert['self_short']}`) — "
                f"run `git pull` before editing"
            )
        lines.append("")

    if not members:
        lines.append("*No teammates currently listed in the live presence mirror.*")
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append("## Teammates with dirty files")
    lines.append("")
    for m in members:
        if not isinstance(m, dict):
            continue
        handle = m.get("handle") or m.get("name") or "(unknown)"
        branch = m.get("branch") or "?"
        last_seen = m.get("last_seen") or ""
        files = m.get("files") or []
        if not isinstance(files, list):
            files = []
        lines.append(f"### @{handle} · {branch} · last seen {last_seen}")
        if not files:
            lines.append("- _(clean)_")
        else:
            for f in files:
                if not isinstance(f, dict):
                    continue
                path = f.get("path") or "?"
                added = int(f.get("lines_added") or 0)
                removed = int(f.get("lines_removed") or 0)
                tag = " **new**" if f.get("untracked") else ""
                # Shorthand: path (+/-) — easy to grep.
                lines.append(f"- `{path}` (+{added}/-{removed}){tag}")
        lines.append("")

    lines.append("## Shorthand index")
    lines.append("")
    files_index = body.get("files_index")
    if isinstance(files_index, dict) and files_index:
        for path in sorted(files_index.keys()):
            entries = files_index.get(path)
            if not isinstance(entries, list):
                continue
            bits = []
            for e in entries:
                if not isinstance(e, dict):
                    continue
                if e.get("self"):
                    bits.append("you")
                    continue
                h = e.get("handle") or e.get("name") or "?"
                bits.append(f"@{h}")
            lines.append(f"- `{path}` → {', '.join(bits)}")
    else:
        lines.append("_Empty._")
    lines.append("")
    return "\n".join(lines) + "\n"


def write_team_editing_brief(
    bundle_root: Path,
    body: dict[str, Any],
    *,
    active_edits: list[dict[str, Any]] | None = None,
) -> bool:
    """Write ``.spec/team-editing-brief.md`` next to ``team-presence.json``.

    Atomic replace on success. Returns ``True`` if the file changed.
    ``active_edits`` carries the same-machine lock list (see
    :mod:`spec_cli.realtime.active_edits`); it's optional so callers
    that don't have an :class:`ActiveEditsStore` handy (older tests,
    one-off scripts) keep working unchanged.
    """
    spec_dir = bundle_root / ".spec"
    target = spec_dir / TEAM_EDITING_BRIEF_FILENAME
    text = render_team_editing_brief(body, active_edits=active_edits)
    try:
        spec_dir.mkdir(parents=True, exist_ok=True)
        tmp_fd, tmp_name = tempfile.mkstemp(
            prefix=f"{TEAM_EDITING_BRIEF_FILENAME}.",
            suffix=".tmp",
            dir=str(spec_dir),
        )
        try:
            with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
                f.write(text)
                f.flush()
                try:
                    os.fsync(f.fileno())
                except OSError:
                    pass
            os.replace(tmp_name, target)
        except OSError:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise
    except OSError:
        return False

    return True


__all__ = [
    "DEFAULT_LOCKS_MIRROR_STALE_SECS",
    "TEAM_EDITING_BRIEF_FILENAME",
    "_compute_pull_alerts",
    "render_team_editing_brief",
    "team_presence_mirror_stale",
    "write_team_editing_brief",
]
